### ISSUE TITLE
Broken Image

### ISSUE THREAD

**Issue by kidman007** [ismayc/moderndiver-book#2]
Hello, 

Just wanted to give you a heads up that figure 6.2 isn't rendering. I just see a big white box.

**Comment by ismayc** [comment]
Thanks for bringing this to our attention.  It appears the shiny app embedded there is not loading inside the book.  It does work if you go to the link ( https://ismay.shinyapps.io/okcupidheights/ ).  I will look into why this is not appearing in the book as it did before though.

**Comment by ismayc** [comment]
I reverted to just using a screenshot instead and having the link to the shiny app be near:  https://ismayc.github.io/moderndiver-book/6-sim.html#visualizing-sampling
