### ISSUE TITLE
Weary wariness

### ISSUE THREAD

**Issue by CamilleFairbourn** [ismayc/moderndiver-book#4]
In section 2.3 you have the sentence: "By the end of this book, you’ll be able to better understand whether these claims should be trusted or whether we should be weary."

While I'm sure studying statistics makes people weary on occasion, I believe the word you want here is "wary".

Cheers!

**Comment by ismayc** [comment]
Ha!  Freudian slip possibly?  I'll fix that now.  Thanks!

**Comment by ismayc** [comment]
Fixed.  https://github.com/ismayc/moderndiver-book/commit/f70da10e336dca3ee444e0a16b2a3d78313430ba
