### ISSUE TITLE
3.2 Markdown structure error

### ISSUE THREAD

**Issue by Sirhurryup** [ismayc/moderndiver-book#6]
Following the code in the "Modern Drive" markdown book located on bookdown.org I encounter the follow errors in the .md html output after running data(flights). Per Ismay book "Getting used to R, Studio, and R Markdown" there was comment about chunks--calling functions listed above will result in error if not called in the current chunk. Something to that effect. For the remainder of the chapter 3, I had to use the eval function to bypass the .md error in the console otherwise all processes halted. Any thoughts or instruction on where I went wrong?

**Comment by rudeboybert** [comment]
Sorry for the delay in responding.

What errors are you getting? I'm having a bit of trouble understanding. A ["Minimal, Complete, and Verifiable example"](https://stackoverflow.com/help/mcve) of your error would be helpful.
